package com.discoverer.exemplary.api

import com.discoverer.exemplary.model.Constants
import com.discoverer.exemplary.model.MovieInfo
import com.discoverer.exemplary.model.SearchResult
import retrofit2.Response


/**
 * Implementation of the ApiHelper interface: in this case, it simply uses the class generated by Retrofit to query the web API.
 *
 * @param apiService An object of a class generated by Retrofit that actually implements calling the web for this API.
 */
class ApiHelperImpl(private val apiService: ApiService) : ApiHelper {

    /**
     * Method to search for all movies that match a given title via the web API.
     *
     * @param title The title to query movies about.
     */
    override suspend fun searchMovies(title: String): Response<SearchResult> = apiService.searchMovies(Constants.API_KEY, title)

    /**
     * Method to get specific information about a given movie, identified by its IMDb ID.
     *
     * @param imdbId The IMDb ID of the movie that we want information about.
     */
    override suspend fun getMovieInfo(imdbId: String): Response<MovieInfo> = apiService.getMovieInfo(Constants.API_KEY, imdbId)

} // ApiHelperImpl class
